-- Schema for churn_prepared_transformed_table
CREATE TABLE churn_prepared_transformed_table (
    SeniorCitizen REAL,
    tenure REAL,
    MonthlyCharges REAL,
    TotalCharges REAL,
    Churn REAL,
    gender_Male TEXT,
    Partner_Yes TEXT,
    Dependents_Yes TEXT,
    PhoneService_Yes TEXT,
    MultipleLines_No phone service TEXT,
    MultipleLines_Yes TEXT,
    InternetService_Fiber optic TEXT,
    InternetService_No TEXT,
    OnlineSecurity_No internet service TEXT,
    OnlineSecurity_Yes TEXT,
    OnlineBackup_No internet service TEXT,
    OnlineBackup_Yes TEXT,
    DeviceProtection_No internet service TEXT,
    DeviceProtection_Yes TEXT,
    TechSupport_No internet service TEXT,
    TechSupport_Yes TEXT,
    StreamingTV_No internet service TEXT,
    StreamingTV_Yes TEXT,
    StreamingMovies_No internet service TEXT,
    StreamingMovies_Yes TEXT,
    Contract_One year TEXT,
    Contract_Two year TEXT,
    PaperlessBilling_Yes TEXT,
    PaymentMethod_Credit card (automatic) TEXT,
    PaymentMethod_Electronic check TEXT,
    PaymentMethod_Mailed check TEXT,
    TotalSpend REAL,
    TenureYears REAL,
    AvgMonthlySpend REAL
);

-- Schema for users_prepared_transformed_table
CREATE TABLE users_prepared_transformed_table (
    id REAL,
    name_Clementina DuBuque TEXT,
    name_Clementine Bauch TEXT,
    name_Ervin Howell TEXT,
    name_Glenna Reichert TEXT,
    name_Kurtis Weissnat TEXT,
    name_Leanne Graham TEXT,
    name_Mrs. Dennis Schulist TEXT,
    name_Nicholas Runolfsdottir V TEXT,
    name_Patricia Lebsack TEXT,
    username_Bret TEXT,
    username_Delphine TEXT,
    username_Elwyn.Skiles TEXT,
    username_Kamren TEXT,
    username_Karianne TEXT,
    username_Leopoldo_Corkery TEXT,
    username_Maxime_Nienow TEXT,
    username_Moriah.Stanton TEXT,
    username_Samantha TEXT,
    email_Julianne.OConner@kory.org TEXT,
    email_Karley_Dach@jasper.info TEXT,
    email_Lucio_Hettinger@annie.ca TEXT,
    email_Nathan@yesenia.net TEXT,
    email_Rey.Padberg@karina.biz TEXT,
    email_Shanna@melissa.tv TEXT,
    email_Sherwood@rosamond.me TEXT,
    email_Sincere@april.biz TEXT,
    email_Telly.Hoeger@billy.biz TEXT,
    address_{'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}} TEXT,
    address_{'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}} TEXT,
    address_{'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}} TEXT,
    address_{'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}} TEXT,
    address_{'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}} TEXT,
    address_{'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}} TEXT,
    address_{'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}} TEXT,
    address_{'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}} TEXT,
    address_{'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}} TEXT,
    phone_(775)976-6794 x41206 TEXT,
    phone_010-692-6593 x09125 TEXT,
    phone_024-648-3804 TEXT,
    phone_1-463-123-4447 TEXT,
    phone_1-477-935-8478 x6430 TEXT,
    phone_1-770-736-8031 x56442 TEXT,
    phone_210.067.6132 TEXT,
    phone_493-170-9623 x156 TEXT,
    phone_586.493.6943 x140 TEXT,
    website_anastasia.net TEXT,
    website_conrad.com TEXT,
    website_demarco.info TEXT,
    website_elvis.io TEXT,
    website_hildegard.org TEXT,
    website_jacynthe.com TEXT,
    website_kale.biz TEXT,
    website_ola.org TEXT,
    website_ramiro.info TEXT,
    company_{'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'} TEXT,
    company_{'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'} TEXT,
    company_{'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'} TEXT,
    company_{'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'} TEXT,
    company_{'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'} TEXT,
    company_{'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'} TEXT,
    company_{'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'} TEXT,
    company_{'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'} TEXT,
    company_{'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'} TEXT
);

